#pragma once

#include <filesystem>
#include <iostream>
#include <oatpp-websocket/Handshaker.hpp>
#include <oatpp/macro/codegen.hpp>
#include <oatpp/macro/component.hpp>
#include <oatpp/network/ConnectionHandler.hpp>
#include <oatpp/web/server/api/ApiController.hpp>

extern std::unordered_map<std::string, std::string> ContentTypes;

#include OATPP_CODEGEN_BEGIN(ApiController)

class WebSocketService : public oatpp::web::server::api::ApiController
{
    typedef WebSocketService __ControllerType;

  private:
    OATPP_COMPONENT(std::shared_ptr<oatpp::network::ConnectionHandler>, websocketConnectionHandler, "websocket");

    constexpr static std::string www_path = "www";

  public:
    WebSocketService(OATPP_COMPONENT(std::shared_ptr<ObjectMapper>, objectMapper))
        : oatpp::web::server::api::ApiController(objectMapper)
    {
    }

  public:
    // clang-format off
    ENDPOINT_ASYNC("GET", "ws", WS)
    {
        ENDPOINT_ASYNC_INIT(WS)

        Action act() override
        {
            auto response = oatpp::websocket::Handshaker::serversideHandshake(request->getHeaders(), controller->websocketConnectionHandler);
            return _return(response);
        }
    };

    ENDPOINT_ASYNC("GET", "*", Wildcard)
    {
        ENDPOINT_ASYNC_INIT(Wildcard)

        Action act() override
        {
            std::string request_path = request->getPathTail();

            std::string combined_path = www_path + "/" + request_path;
            std::string full_path = std::filesystem::path(combined_path).lexically_normal().string();

            std::string content_type = "text/html";
            size_t extension_pos = full_path.rfind('.');
            if (extension_pos != std::string::npos)
            {
                std::string extension = full_path.substr(extension_pos + 1);
                auto it = ContentTypes.find(extension);
                if (it != ContentTypes.end())
                {
                    content_type = it->second;
                }
            }
            else
            {
                // The extension is missing because it's an application route
                full_path = www_path + "/index.html";
                content_type = "text/html";
            }

            auto file = oatpp::String::loadFromFile(full_path.c_str());
            if (file)
            {
                auto response = this->controller->createResponse(Status::CODE_200, file);
                response->putHeader(Header::CONTENT_TYPE, content_type);
                return _return(response);
            }

            return _return(controller->createResponse(Status::CODE_404, "File not found"));
        };
    };
};
// clang-format on

#include OATPP_CODEGEN_END(ApiController)

std::unordered_map<std::string, std::string> ContentTypes{
    {                   "323",                                                              "text/h323"},
    {                   "3g2",                                                            "video/3gpp2"},
    {                   "3gp",                                                             "video/3gpp"},
    {                  "3gp2",                                                            "video/3gpp2"},
    {                  "3gpp",                                                             "video/3gpp"},
    {                    "7z",                                            "application/x-7z-compressed"},
    {                    "aa",                                                          "audio/audible"},
    {                   "AAC",                                                              "audio/aac"},
    {                   "aaf",                                               "application/octet-stream"},
    {                   "aax",                                                    "audio/vndaudibleaax"},
    {                   "ac3",                                                              "audio/ac3"},
    {                   "aca",                                               "application/octet-stream"},
    {                 "accda",                                              "application/msaccessaddin"},
    {                 "accdb",                                                   "application/msaccess"},
    {                 "accdc",                                                "application/msaccesscab"},
    {                 "accde",                                                   "application/msaccess"},
    {                 "accdr",                                            "application/msaccessruntime"},
    {                 "accdt",                                                   "application/msaccess"},
    {                 "accdw",                                     "application/msaccesswebapplication"},
    {                 "accft",                                          "application/msaccessftemplate"},
    {                   "acx",                                   "application/internet-property-stream"},
    {                 "AddIn",                                                               "text/xml"},
    {                   "ade",                                                   "application/msaccess"},
    {           "adobebridge",                                               "application/x-bridge-url"},
    {                   "adp",                                                   "application/msaccess"},
    {                   "ADT",                                                      "audio/vnddlnaadts"},
    {                  "ADTS",                                                              "audio/aac"},
    {                   "afm",                                               "application/octet-stream"},
    {                    "ai",                                                 "application/postscript"},
    {                   "aif",                                                             "audio/aiff"},
    {                  "aifc",                                                             "audio/aiff"},
    {                  "aiff",                                                             "audio/aiff"},
    {                   "air",              "application/vndadobeair-application-installer-package+zip"},
    {                   "amc",                                                       "application/mpeg"},
    {                   "anx",                                                    "application/annodex"},
    {                   "apk",                                  "application/vndandroidpackage-archive"},
    {           "application",                                           "application/x-ms-application"},
    {                   "art",                                                             "image/x-jg"},
    {                   "asa",                                                        "application/xml"},
    {                  "asax",                                                        "application/xml"},
    {                  "ascx",                                                        "application/xml"},
    {                   "asd",                                               "application/octet-stream"},
    {                   "asf",                                                         "video/x-ms-asf"},
    {                  "ashx",                                                        "application/xml"},
    {                   "asi",                                               "application/octet-stream"},
    {                   "asm",                                                             "text/plain"},
    {                  "asmx",                                                        "application/xml"},
    {                  "aspx",                                                        "application/xml"},
    {                   "asr",                                                         "video/x-ms-asf"},
    {                   "asx",                                                         "video/x-ms-asf"},
    {                  "atom",                                                   "application/atom+xml"},
    {                    "au",                                                            "audio/basic"},
    {                   "avi",                                                        "video/x-msvideo"},
    {                   "axa",                                                          "audio/annodex"},
    {                   "axs",                                                  "application/olescript"},
    {                   "axv",                                                          "video/annodex"},
    {                   "bas",                                                             "text/plain"},
    {                 "bcpio",                                                    "application/x-bcpio"},
    {                   "bin",                                               "application/octet-stream"},
    {                   "bmp",                                                              "image/bmp"},
    {                     "c",                                                             "text/plain"},
    {                   "cab",                                               "application/octet-stream"},
    {                   "caf",                                                            "audio/x-caf"},
    {                  "calx",                                           "application/vndms-officecalx"},
    {                   "cat",                                            "application/vndms-pkiseccat"},
    {                    "cc",                                                             "text/plain"},
    {                    "cd",                                                             "text/plain"},
    {                  "cdda",                                                             "audio/aiff"},
    {                   "cdf",                                                      "application/x-cdf"},
    {                   "cer",                                             "application/x-x509-ca-cert"},
    {                   "cfg",                                                             "text/plain"},
    {                   "chm",                                               "application/octet-stream"},
    {                 "class",                                              "application/x-java-applet"},
    {                   "clp",                                                   "application/x-msclip"},
    {                   "cmd",                                                             "text/plain"},
    {                   "cmx",                                                            "image/x-cmx"},
    {                   "cnf",                                                             "text/plain"},
    {                   "cod",                                                          "image/cis-cod"},
    {                "config",                                                        "application/xml"},
    {               "contact",                                                      "text/x-ms-contact"},
    {              "coverage",                                                        "application/xml"},
    {                  "cpio",                                                     "application/x-cpio"},
    {                   "cpp",                                                             "text/plain"},
    {                   "crd",                                               "application/x-mscardfile"},
    {                   "crl",                                                   "application/pkix-crl"},
    {                   "crt",                                             "application/x-x509-ca-cert"},
    {                    "cs",                                                             "text/plain"},
    {               "csdproj",                                                             "text/plain"},
    {                   "csh",                                                      "application/x-csh"},
    {                "csproj",                                                             "text/plain"},
    {                   "css",                                                               "text/css"},
    {                   "csv",                                                               "text/csv"},
    {                   "cur",                                               "application/octet-stream"},
    {                   "cxx",                                                             "text/plain"},
    {                   "dat",                                               "application/octet-stream"},
    {            "datasource",                                                        "application/xml"},
    {                "dbproj",                                                             "text/plain"},
    {                   "dcr",                                                 "application/x-director"},
    {                   "def",                                                             "text/plain"},
    {                "deploy",                                               "application/octet-stream"},
    {                   "der",                                             "application/x-x509-ca-cert"},
    {                  "dgml",                                                        "application/xml"},
    {                   "dib",                                                              "image/bmp"},
    {                   "dif",                                                             "video/x-dv"},
    {                   "dir",                                                 "application/x-director"},
    {                 "disco",                                                               "text/xml"},
    {                  "divx",                                                             "video/divx"},
    {                   "dll",                                               "application/x-msdownload"},
    {             "dllconfig",                                                               "text/xml"},
    {                   "dlm",                                                               "text/dlm"},
    {                   "doc",                                                     "application/msword"},
    {                  "docm",                           "application/vndms-worddocumentmacroEnabled12"},
    {                  "docx",   "application/vndopenxmlformats-officedocumentwordprocessingmldocument"},
    {                   "dot",                                                     "application/msword"},
    {                  "dotm",                           "application/vndms-wordtemplatemacroEnabled12"},
    {                  "dotx",   "application/vndopenxmlformats-officedocumentwordprocessingmltemplate"},
    {                   "dsp",                                               "application/octet-stream"},
    {                   "dsw",                                                             "text/plain"},
    {                   "dtd",                                                               "text/xml"},
    {             "dtsConfig",                                                               "text/xml"},
    {                    "dv",                                                             "video/x-dv"},
    {                   "dvi",                                                      "application/x-dvi"},
    {                   "dwf",                                                          "drawing/x-dwf"},
    {                   "dwp",                                               "application/octet-stream"},
    {                   "dxr",                                                 "application/x-director"},
    {                   "eml",                                                         "message/rfc822"},
    {                   "emz",                                               "application/octet-stream"},
    {                   "eot",                                           "application/vndms-fontobject"},
    {                   "eps",                                                 "application/postscript"},
    {                   "etl",                                                        "application/etl"},
    {                   "etx",                                                          "text/x-setext"},
    {                   "evy",                                                      "application/envoy"},
    {                   "exe",                                               "application/octet-stream"},
    {             "execonfig",                                                               "text/xml"},
    {                   "fdf",                                                     "application/vndfdf"},
    {                   "fif",                                                   "application/fractals"},
    {               "filters",                                                        "application/xml"},
    {                   "fla",                                               "application/octet-stream"},
    {                  "flac",                                                             "audio/flac"},
    {                   "flr",                                                         "x-world/x-vrml"},
    {                   "flv",                                                            "video/x-flv"},
    {              "fsscript",                                              "application/fsharp-script"},
    {                   "fsx",                                              "application/fsharp-script"},
    {           "generictest",                                                        "application/xml"},
    {                   "gif",                                                              "image/gif"},
    {                   "gpx",                                                    "application/gpx+xml"},
    {                 "group",                                                        "text/x-ms-group"},
    {                   "gsm",                                                            "audio/x-gsm"},
    {                  "gtar",                                                     "application/x-gtar"},
    {                    "gz",                                                     "application/x-gzip"},
    {                     "h",                                                             "text/plain"},
    {                   "hdf",                                                      "application/x-hdf"},
    {                  "hdml",                                                            "text/x-hdml"},
    {                   "hhc",                                                "application/x-oleobject"},
    {                   "hhk",                                               "application/octet-stream"},
    {                   "hhp",                                               "application/octet-stream"},
    {                   "hlp",                                                     "application/winhlp"},
    {                   "hpp",                                                             "text/plain"},
    {                   "hqx",                                               "application/mac-binhex40"},
    {                   "hta",                                                        "application/hta"},
    {                   "htc",                                                       "text/x-component"},
    {                   "htm",                                                              "text/html"},
    {                  "html",                                                              "text/html"},
    {                   "htt",                                                       "text/webviewhtml"},
    {                   "hxa",                                                        "application/xml"},
    {                   "hxc",                                                        "application/xml"},
    {                   "hxd",                                               "application/octet-stream"},
    {                   "hxe",                                                        "application/xml"},
    {                   "hxf",                                                        "application/xml"},
    {                   "hxh",                                               "application/octet-stream"},
    {                   "hxi",                                               "application/octet-stream"},
    {                   "hxk",                                                        "application/xml"},
    {                   "hxq",                                               "application/octet-stream"},
    {                   "hxr",                                               "application/octet-stream"},
    {                   "hxs",                                               "application/octet-stream"},
    {                   "hxt",                                                              "text/html"},
    {                   "hxv",                                                        "application/xml"},
    {                   "hxw",                                               "application/octet-stream"},
    {                   "hxx",                                                             "text/plain"},
    {                     "i",                                                             "text/plain"},
    {                   "ico",                                                           "image/x-icon"},
    {                   "ics",                                               "application/octet-stream"},
    {                   "idl",                                                             "text/plain"},
    {                   "ief",                                                              "image/ief"},
    {                   "iii",                                                   "application/x-iphone"},
    {                   "inc",                                                             "text/plain"},
    {                   "inf",                                               "application/octet-stream"},
    {                   "ini",                                                             "text/plain"},
    {                   "inl",                                                             "text/plain"},
    {                   "ins",                                          "application/x-internet-signup"},
    {                   "ipa",                                               "application/x-itunes-ipa"},
    {                   "ipg",                                               "application/x-itunes-ipg"},
    {                "ipproj",                                                             "text/plain"},
    {                  "ipsw",                                              "application/x-itunes-ipsw"},
    {                   "iqy",                                                          "text/x-ms-iqy"},
    {                   "isp",                                          "application/x-internet-signup"},
    {                   "ite",                                               "application/x-itunes-ite"},
    {                  "itlp",                                              "application/x-itunes-itlp"},
    {                  "itms",                                              "application/x-itunes-itms"},
    {                  "itpc",                                              "application/x-itunes-itpc"},
    {                   "IVF",                                                            "video/x-ivf"},
    {                   "jar",                                               "application/java-archive"},
    {                  "java",                                               "application/octet-stream"},
    {                   "jck",                                               "application/liquidmotion"},
    {                   "jcz",                                               "application/liquidmotion"},
    {                  "jfif",                                                            "image/pjpeg"},
    {                  "jnlp",                                           "application/x-java-jnlp-file"},
    {                   "jpb",                                               "application/octet-stream"},
    {                   "jpe",                                                             "image/jpeg"},
    {                  "jpeg",                                                             "image/jpeg"},
    {                   "jpg",                                                             "image/jpeg"},
    {                    "js",                                                 "application/javascript"},
    {                  "json",                                                       "application/json"},
    {                   "jsx",                                                           "text/jscript"},
    {                "jsxbin",                                                             "text/plain"},
    {                 "latex",                                                    "application/x-latex"},
    {            "library-ms",                                        "application/windows-library+xml"},
    {                   "lit",                                                "application/x-ms-reader"},
    {              "loadtest",                                                        "application/xml"},
    {                   "lpk",                                               "application/octet-stream"},
    {                   "lsf",                                                         "video/x-la-asf"},
    {                   "lst",                                                             "text/plain"},
    {                   "lsx",                                                         "video/x-la-asf"},
    {                   "lzh",                                               "application/octet-stream"},
    {                   "m13",                                              "application/x-msmediaview"},
    {                   "m14",                                              "application/x-msmediaview"},
    {                   "m1v",                                                             "video/mpeg"},
    {                   "m2t",                                                  "video/vnddlnampeg-tts"},
    {                  "m2ts",                                                  "video/vnddlnampeg-tts"},
    {                   "m2v",                                                             "video/mpeg"},
    {                   "m3u",                                                        "audio/x-mpegurl"},
    {                  "m3u8",                                                        "audio/x-mpegurl"},
    {                   "m4a",                                                              "audio/m4a"},
    {                   "m4b",                                                              "audio/m4b"},
    {                   "m4p",                                                              "audio/m4p"},
    {                   "m4r",                                                            "audio/x-m4r"},
    {                   "m4v",                                                            "video/x-m4v"},
    {                   "mac",                                                       "image/x-macpaint"},
    {                   "mak",                                                             "text/plain"},
    {                   "man",                                                "application/x-troff-man"},
    {              "manifest",                                              "application/x-ms-manifest"},
    {                   "map",                                                             "text/plain"},
    {                "master",                                                        "application/xml"},
    {                   "mda",                                                   "application/msaccess"},
    {                   "mdb",                                                 "application/x-msaccess"},
    {                   "mde",                                                   "application/msaccess"},
    {                   "mdp",                                               "application/octet-stream"},
    {                    "me",                                                 "application/x-troff-me"},
    {                   "mfp",                                          "application/x-shockwave-flash"},
    {                   "mht",                                                         "message/rfc822"},
    {                 "mhtml",                                                         "message/rfc822"},
    {                   "mid",                                                              "audio/mid"},
    {                  "midi",                                                              "audio/mid"},
    {                   "mix",                                               "application/octet-stream"},
    {                    "mk",                                                             "text/plain"},
    {                   "mmf",                                                     "application/x-smaf"},
    {                   "mno",                                                               "text/xml"},
    {                   "mny",                                                  "application/x-msmoney"},
    {                   "mod",                                                             "video/mpeg"},
    {                   "mov",                                                        "video/quicktime"},
    {                 "movie",                                                      "video/x-sgi-movie"},
    {                   "mp2",                                                             "video/mpeg"},
    {                  "mp2v",                                                             "video/mpeg"},
    {                   "mp3",                                                             "audio/mpeg"},
    {                   "mp4",                                                              "video/mp4"},
    {                  "mp4v",                                                              "video/mp4"},
    {                   "mpa",                                                             "video/mpeg"},
    {                   "mpe",                                                             "video/mpeg"},
    {                  "mpeg",                                                             "video/mpeg"},
    {                   "mpf",                                         "application/vndms-mediapackage"},
    {                   "mpg",                                                             "video/mpeg"},
    {                   "mpp",                                              "application/vndms-project"},
    {                  "mpv2",                                                             "video/mpeg"},
    {                   "mqv",                                                        "video/quicktime"},
    {                    "ms",                                                 "application/x-troff-ms"},
    {                   "msi",                                               "application/octet-stream"},
    {                   "mso",                                               "application/octet-stream"},
    {                   "mts",                                                  "video/vnddlnampeg-tts"},
    {                   "mtx",                                                        "application/xml"},
    {                   "mvb",                                              "application/x-msmediaview"},
    {                   "mvc",                                            "application/x-miva-compiled"},
    {                   "mxp",                                                     "application/x-mmxp"},
    {                    "nc",                                                   "application/x-netcdf"},
    {                   "nsc",                                                         "video/x-ms-asf"},
    {                   "nws",                                                         "message/rfc822"},
    {                   "ocx",                                               "application/octet-stream"},
    {                   "oda",                                                        "application/oda"},
    {                   "odb",                               "application/vndoasisopendocumentdatabase"},
    {                   "odc",                                  "application/vndoasisopendocumentchart"},
    {                   "odf",                                "application/vndoasisopendocumentformula"},
    {                   "odg",                               "application/vndoasisopendocumentgraphics"},
    {                   "odh",                                                             "text/plain"},
    {                   "odi",                                  "application/vndoasisopendocumentimage"},
    {                   "odl",                                                             "text/plain"},
    {                   "odm",                            "application/vndoasisopendocumenttext-master"},
    {                   "odp",                           "application/vndoasisopendocumentpresentation"},
    {                   "ods",                            "application/vndoasisopendocumentspreadsheet"},
    {                   "odt",                                   "application/vndoasisopendocumenttext"},
    {                   "oga",                                                              "audio/ogg"},
    {                   "ogg",                                                              "audio/ogg"},
    {                   "ogv",                                                              "video/ogg"},
    {                   "ogx",                                                        "application/ogg"},
    {                   "one",                                                    "application/onenote"},
    {                  "onea",                                                    "application/onenote"},
    {                "onepkg",                                                    "application/onenote"},
    {                "onetmp",                                                    "application/onenote"},
    {                "onetoc",                                                    "application/onenote"},
    {               "onetoc2",                                                    "application/onenote"},
    {                  "opus",                                                              "audio/ogg"},
    {           "orderedtest",                                                        "application/xml"},
    {                  "osdx",                                  "application/opensearchdescription+xml"},
    {                   "otf",                                                  "application/font-sfnt"},
    {                   "otg",                      "application/vndoasisopendocumentgraphics-template"},
    {                   "oth",                               "application/vndoasisopendocumenttext-web"},
    {                   "otp",                  "application/vndoasisopendocumentpresentation-template"},
    {                   "ots",                   "application/vndoasisopendocumentspreadsheet-template"},
    {                   "ott",                          "application/vndoasisopendocumenttext-template"},
    {                   "oxt",                                  "application/vndopenofficeorgextension"},
    {                   "p10",                                                     "application/pkcs10"},
    {                   "p12",                                                   "application/x-pkcs12"},
    {                   "p7b",                                       "application/x-pkcs7-certificates"},
    {                   "p7c",                                                 "application/pkcs7-mime"},
    {                   "p7m",                                                 "application/pkcs7-mime"},
    {                   "p7r",                                        "application/x-pkcs7-certreqresp"},
    {                   "p7s",                                            "application/pkcs7-signature"},
    {                   "pbm",                                                "image/x-portable-bitmap"},
    {                 "pcast",                                                  "application/x-podcast"},
    {                   "pct",                                                             "image/pict"},
    {                   "pcx",                                               "application/octet-stream"},
    {                   "pcz",                                               "application/octet-stream"},
    {                   "pdf",                                                        "application/pdf"},
    {                   "pfb",                                               "application/octet-stream"},
    {                   "pfm",                                               "application/octet-stream"},
    {                   "pfx",                                                   "application/x-pkcs12"},
    {                   "pgm",                                               "image/x-portable-graymap"},
    {                   "pic",                                                             "image/pict"},
    {                  "pict",                                                             "image/pict"},
    {                "pkgdef",                                                             "text/plain"},
    {              "pkgundef",                                                             "text/plain"},
    {                   "pko",                                               "application/vndms-pkipko"},
    {                   "pls",                                                            "audio/scpls"},
    {                   "pma",                                                  "application/x-perfmon"},
    {                   "pmc",                                                  "application/x-perfmon"},
    {                   "pml",                                                  "application/x-perfmon"},
    {                   "pmr",                                                  "application/x-perfmon"},
    {                   "pmw",                                                  "application/x-perfmon"},
    {                   "png",                                                              "image/png"},
    {                   "pnm",                                                "image/x-portable-anymap"},
    {                   "pnt",                                                       "image/x-macpaint"},
    {                  "pntg",                                                       "image/x-macpaint"},
    {                   "pnz",                                                              "image/png"},
    {                   "pot",                                           "application/vndms-powerpoint"},
    {                  "potm",                     "application/vndms-powerpointtemplatemacroEnabled12"},
    {                  "potx",     "application/vndopenxmlformats-officedocumentpresentationmltemplate"},
    {                   "ppa",                                           "application/vndms-powerpoint"},
    {                  "ppam",                        "application/vndms-powerpointaddinmacroEnabled12"},
    {                   "ppm",                                                "image/x-portable-pixmap"},
    {                   "pps",                                           "application/vndms-powerpoint"},
    {                  "ppsm",                    "application/vndms-powerpointslideshowmacroEnabled12"},
    {                  "ppsx",    "application/vndopenxmlformats-officedocumentpresentationmlslideshow"},
    {                   "ppt",                                           "application/vndms-powerpoint"},
    {                  "pptm",                 "application/vndms-powerpointpresentationmacroEnabled12"},
    {                  "pptx", "application/vndopenxmlformats-officedocumentpresentationmlpresentation"},
    {                   "prf",                                                 "application/pics-rules"},
    {                   "prm",                                               "application/octet-stream"},
    {                   "prx",                                               "application/octet-stream"},
    {                    "ps",                                                 "application/postscript"},
    {                  "psc1",                                                 "application/PowerShell"},
    {                   "psd",                                               "application/octet-stream"},
    {                 "psess",                                                        "application/xml"},
    {                   "psm",                                               "application/octet-stream"},
    {                   "psp",                                               "application/octet-stream"},
    {                   "pub",                                              "application/x-mspublisher"},
    {                   "pwz",                                           "application/vndms-powerpoint"},
    {                   "qht",                                                  "text/x-html-insertion"},
    {                  "qhtm",                                                  "text/x-html-insertion"},
    {                    "qt",                                                        "video/quicktime"},
    {                   "qti",                                                      "image/x-quicktime"},
    {                  "qtif",                                                      "image/x-quicktime"},
    {                   "qtl",                                          "application/x-quicktimeplayer"},
    {                   "qxd",                                               "application/octet-stream"},
    {                    "ra",                                                   "audio/x-pn-realaudio"},
    {                   "ram",                                                   "audio/x-pn-realaudio"},
    {                   "rar",                                           "application/x-rar-compressed"},
    {                   "ras",                                                     "image/x-cmu-raster"},
    {                   "rat",                                                   "application/rat-file"},
    {                    "rc",                                                             "text/plain"},
    {                   "rc2",                                                             "text/plain"},
    {                   "rct",                                                             "text/plain"},
    {                  "rdlc",                                                        "application/xml"},
    {                   "reg",                                                             "text/plain"},
    {                  "resx",                                                        "application/xml"},
    {                    "rf",                                                  "image/vndrn-realflash"},
    {                   "rgb",                                                            "image/x-rgb"},
    {                   "rgs",                                                             "text/plain"},
    {                    "rm",                                            "application/vndrn-realmedia"},
    {                   "rmi",                                                              "audio/mid"},
    {                   "rmp",                                     "application/vndrn-rn_music_package"},
    {                  "roff",                                                    "application/x-troff"},
    {                   "rpm",                                            "audio/x-pn-realaudio-plugin"},
    {                   "rqy",                                                          "text/x-ms-rqy"},
    {                   "rtf",                                                        "application/rtf"},
    {                   "rtx",                                                          "text/richtext"},
    {               "ruleset",                                                        "application/xml"},
    {                     "s",                                                             "text/plain"},
    {            "safariextz",                                        "application/x-safari-safariextz"},
    {                   "scd",                                               "application/x-msschedule"},
    {                   "scr",                                                             "text/plain"},
    {                   "sct",                                                         "text/scriptlet"},
    {                   "sd2",                                                            "audio/x-sd2"},
    {                   "sdp",                                                        "application/sdp"},
    {                   "sea",                                               "application/octet-stream"},
    {    "searchConnector-ms",                               "application/windows-search-connector+xml"},
    {                "setpay",                                     "application/set-payment-initiation"},
    {                "setreg",                                "application/set-registration-initiation"},
    {              "settings",                                                        "application/xml"},
    {                 "sgimb",                                                    "application/x-sgimb"},
    {                  "sgml",                                                              "text/sgml"},
    {                    "sh",                                                       "application/x-sh"},
    {                  "shar",                                                     "application/x-shar"},
    {                 "shtml",                                                              "text/html"},
    {                   "sit",                                                  "application/x-stuffit"},
    {               "sitemap",                                                        "application/xml"},
    {                  "skin",                                                        "application/xml"},
    {                  "sldm",                        "application/vndms-powerpointslidemacroEnabled12"},
    {                  "sldx",        "application/vndopenxmlformats-officedocumentpresentationmlslide"},
    {                   "slk",                                                "application/vndms-excel"},
    {                   "sln",                                                             "text/plain"},
    {             "slupkg-ms",                                               "application/x-ms-license"},
    {                   "smd",                                                            "audio/x-smd"},
    {                   "smi",                                               "application/octet-stream"},
    {                   "smx",                                                            "audio/x-smd"},
    {                   "smz",                                                            "audio/x-smd"},
    {                   "snd",                                                            "audio/basic"},
    {               "snippet",                                                        "application/xml"},
    {                   "snp",                                               "application/octet-stream"},
    {                   "sol",                                                             "text/plain"},
    {                   "sor",                                                             "text/plain"},
    {                   "spc",                                       "application/x-pkcs7-certificates"},
    {                   "spl",                                               "application/futuresplash"},
    {                   "spx",                                                              "audio/ogg"},
    {                   "src",                                              "application/x-wais-source"},
    {                   "srf",                                                             "text/plain"},
    {"SSISDeploymentManifest",                                                               "text/xml"},
    {                   "ssm",                                             "application/streamingmedia"},
    {                   "sst",                                         "application/vndms-pkicertstore"},
    {                   "stl",                                               "application/vndms-pkistl"},
    {               "sv4cpio",                                                  "application/x-sv4cpio"},
    {                "sv4crc",                                                   "application/x-sv4crc"},
    {                   "svc",                                                        "application/xml"},
    {                   "svg",                                                          "image/svg+xml"},
    {                   "swf",                                          "application/x-shockwave-flash"},
    {                  "step",                                                       "application/step"},
    {                   "stp",                                                       "application/step"},
    {                     "t",                                                    "application/x-troff"},
    {                   "tar",                                                      "application/x-tar"},
    {                   "tcl",                                                      "application/x-tcl"},
    {         "testrunconfig",                                                        "application/xml"},
    {          "testsettings",                                                        "application/xml"},
    {                   "tex",                                                      "application/x-tex"},
    {                  "texi",                                                  "application/x-texinfo"},
    {               "texinfo",                                                  "application/x-texinfo"},
    {                   "tgz",                                               "application/x-compressed"},
    {                  "thmx",                                          "application/vndms-officetheme"},
    {                   "thn",                                               "application/octet-stream"},
    {                   "tif",                                                             "image/tiff"},
    {                  "tiff",                                                             "image/tiff"},
    {                   "tlh",                                                             "text/plain"},
    {                   "tli",                                                             "text/plain"},
    {                   "toc",                                               "application/octet-stream"},
    {                    "tr",                                                    "application/x-troff"},
    {                   "trm",                                               "application/x-msterminal"},
    {                   "trx",                                                        "application/xml"},
    {                    "ts",                                                  "video/vnddlnampeg-tts"},
    {                   "tsv",                                              "text/tab-separated-values"},
    {                   "ttf",                                                  "application/font-sfnt"},
    {                   "tts",                                                  "video/vnddlnampeg-tts"},
    {                   "txt",                                                             "text/plain"},
    {                   "u32",                                               "application/octet-stream"},
    {                   "uls",                                                              "text/iuls"},
    {                  "user",                                                             "text/plain"},
    {                 "ustar",                                                    "application/x-ustar"},
    {                    "vb",                                                             "text/plain"},
    {               "vbdproj",                                                             "text/plain"},
    {                   "vbk",                                                             "video/mpeg"},
    {                "vbproj",                                                             "text/plain"},
    {                   "vbs",                                                          "text/vbscript"},
    {                   "vcf",                                                           "text/x-vcard"},
    {                "vcproj",                                                        "application/xml"},
    {                   "vcs",                                                             "text/plain"},
    {               "vcxproj",                                                        "application/xml"},
    {               "vddproj",                                                             "text/plain"},
    {                   "vdp",                                                             "text/plain"},
    {                "vdproj",                                                             "text/plain"},
    {                   "vdx",                                          "application/vndms-visioviewer"},
    {                   "vml",                                                               "text/xml"},
    {             "vscontent",                                                        "application/xml"},
    {                  "vsct",                                                               "text/xml"},
    {                   "vsd",                                                   "application/vndvisio"},
    {                   "vsi",                                                     "application/ms-vsi"},
    {                  "vsix",                                                       "application/vsix"},
    {          "vsixlangpack",                                                               "text/xml"},
    {          "vsixmanifest",                                                               "text/xml"},
    {                 "vsmdi",                                                        "application/xml"},
    {                "vspscc",                                                             "text/plain"},
    {                   "vss",                                                   "application/vndvisio"},
    {                 "vsscc",                                                             "text/plain"},
    {            "vssettings",                                                               "text/xml"},
    {                "vssscc",                                                             "text/plain"},
    {                   "vst",                                                   "application/vndvisio"},
    {            "vstemplate",                                                               "text/xml"},
    {                  "vsto",                                                  "application/x-ms-vsto"},
    {                   "vsw",                                                   "application/vndvisio"},
    {                   "vsx",                                                   "application/vndvisio"},
    {                   "vtx",                                                   "application/vndvisio"},
    {                   "wav",                                                              "audio/wav"},
    {                  "wave",                                                              "audio/wav"},
    {                   "wax",                                                         "audio/x-ms-wax"},
    {                   "wbk",                                                     "application/msword"},
    {                  "wbmp",                                                       "image/vndwapwbmp"},
    {                   "wcm",                                                "application/vndms-works"},
    {                   "wdb",                                                "application/vndms-works"},
    {                   "wdp",                                                      "image/vndms-photo"},
    {            "webarchive",                                        "application/x-safari-webarchive"},
    {                  "webm",                                                             "video/webm"},
    {                  "webp",                                                             "image/webp"},
    {               "webtest",                                                        "application/xml"},
    {                   "wiq",                                                        "application/xml"},
    {                   "wiz",                                                     "application/msword"},
    {                   "wks",                                                "application/vndms-works"},
    {                  "WLMP",                                               "application/wlmoviemaker"},
    {           "wlpginstall",                                              "application/x-wlpg-detect"},
    {          "wlpginstall3",                                             "application/x-wlpg3-detect"},
    {                    "wm",                                                          "video/x-ms-wm"},
    {                   "wma",                                                         "audio/x-ms-wma"},
    {                   "wmd",                                                   "application/x-ms-wmd"},
    {                   "wmf",                                               "application/x-msmetafile"},
    {                   "wml",                                                         "text/vndwapwml"},
    {                  "wmlc",                                                 "application/vndwapwmlc"},
    {                  "wmls",                                                   "text/vndwapwmlscript"},
    {                 "wmlsc",                                           "application/vndwapwmlscriptc"},
    {                   "wmp",                                                         "video/x-ms-wmp"},
    {                   "wmv",                                                         "video/x-ms-wmv"},
    {                   "wmx",                                                         "video/x-ms-wmx"},
    {                   "wmz",                                                   "application/x-ms-wmz"},
    {                  "woff",                                                  "application/font-woff"},
    {                   "wpl",                                                  "application/vndms-wpl"},
    {                   "wps",                                                "application/vndms-works"},
    {                   "wri",                                                  "application/x-mswrite"},
    {                   "wrl",                                                         "x-world/x-vrml"},
    {                   "wrz",                                                         "x-world/x-vrml"},
    {                   "wsc",                                                         "text/scriptlet"},
    {                  "wsdl",                                                               "text/xml"},
    {                   "wvx",                                                         "video/x-ms-wvx"},
    {                     "x",                                                    "application/directx"},
    {                   "xaf",                                                         "x-world/x-vrml"},
    {                  "xaml",                                                   "application/xaml+xml"},
    {                   "xap",                                          "application/x-silverlight-app"},
    {                  "xbap",                                                  "application/x-ms-xbap"},
    {                   "xbm",                                                        "image/x-xbitmap"},
    {                   "xdr",                                                             "text/plain"},
    {                   "xht",                                                  "application/xhtml+xml"},
    {                 "xhtml",                                                  "application/xhtml+xml"},
    {                   "xla",                                                "application/vndms-excel"},
    {                  "xlam",                             "application/vndms-exceladdinmacroEnabled12"},
    {                   "xlc",                                                "application/vndms-excel"},
    {                   "xld",                                                "application/vndms-excel"},
    {                   "xlk",                                                "application/vndms-excel"},
    {                   "xll",                                                "application/vndms-excel"},
    {                   "xlm",                                                "application/vndms-excel"},
    {                   "xls",                                                "application/vndms-excel"},
    {                  "xlsb",                       "application/vndms-excelsheetbinarymacroEnabled12"},
    {                  "xlsm",                             "application/vndms-excelsheetmacroEnabled12"},
    {                  "xlsx",         "application/vndopenxmlformats-officedocumentspreadsheetmlsheet"},
    {                   "xlt",                                                "application/vndms-excel"},
    {                  "xltm",                          "application/vndms-exceltemplatemacroEnabled12"},
    {                  "xltx",      "application/vndopenxmlformats-officedocumentspreadsheetmltemplate"},
    {                   "xlw",                                                "application/vndms-excel"},
    {                   "xml",                                                               "text/xml"},
    {                  "xmta",                                                        "application/xml"},
    {                   "xof",                                                         "x-world/x-vrml"},
    {                  "XOML",                                                             "text/plain"},
    {                   "xpm",                                                        "image/x-xpixmap"},
    {                   "xps",                                          "application/vndms-xpsdocument"},
    {                "xrm-ms",                                                               "text/xml"},
    {                   "xsc",                                                        "application/xml"},
    {                   "xsd",                                                               "text/xml"},
    {                   "xsf",                                                               "text/xml"},
    {                   "xsl",                                                               "text/xml"},
    {                  "xslt",                                                               "text/xml"},
    {                   "xsn",                                               "application/octet-stream"},
    {                   "xss",                                                        "application/xml"},
    {                  "xspf",                                                   "application/xspf+xml"},
    {                   "xtp",                                               "application/octet-stream"},
    {                   "xwd",                                                    "image/x-xwindowdump"},
    {                     "z",                                                 "application/x-compress"},
    {                   "zip",                                                        "application/zip"},
    {                   "fsx",                                              "application/fsharp-script"},
    {                   "adp",                                                   "application/msaccess"},
    {                   "doc",                                                     "application/msword"},
    {                   "bin",                                               "application/octet-stream"},
    {                   "one",                                                    "application/onenote"},
    {                   "eps",                                                 "application/postscript"},
    {                  "step",                                                       "application/step"},
    {                   "xls",                                                "application/vndms-excel"},
    {                   "ppt",                                           "application/vndms-powerpoint"},
    {                   "wks",                                                "application/vndms-works"},
    {                   "vsd",                                                   "application/vndvisio"},
    {                   "dir",                                                 "application/x-director"},
    {                   "swf",                                          "application/x-shockwave-flash"},
    {                   "cer",                                             "application/x-x509-ca-cert"},
    {                   "zip",                                           "application/x-zip-compressed"},
    {                 "xhtml",                                                  "application/xhtml+xml"},
    {                   "xml",                                                        "application/xml"},
    {                   "AAC",                                                              "audio/aac"},
    {                  "aiff",                                                             "audio/aiff"},
    {                   "snd",                                                            "audio/basic"},
    {                  "midi",                                                              "audio/mid"},
    {                   "wav",                                                              "audio/wav"},
    {                   "m4a",                                                            "audio/x-m4a"},
    {                   "m3u",                                                        "audio/x-mpegurl"},
    {                    "ra",                                                   "audio/x-pn-realaudio"},
    {                   "smd",                                                            "audio/x-smd"},
    {                   "bmp",                                                              "image/bmp"},
    {                   "jpg",                                                             "image/jpeg"},
    {                   "pic",                                                             "image/pict"},
    {                   "png",                                                              "image/png"},
    {                  "tiff",                                                             "image/tiff"},
    {                   "mac",                                                       "image/x-macpaint"},
    {                   "qti",                                                      "image/x-quicktime"},
    {                   "eml",                                                         "message/rfc822"},
    {                  "html",                                                              "text/html"},
    {                   "txt",                                                             "text/plain"},
    {                   "wsc",                                                         "text/scriptlet"},
    {                   "xml",                                                               "text/xml"},
    {                   "3gp",                                                             "video/3gpp"},
    {                  "3gp2",                                                            "video/3gpp2"},
    {                   "mp4",                                                              "video/mp4"},
    {                   "mpg",                                                             "video/mpeg"},
    {                   "mov",                                                        "video/quicktime"},
    {                   "m2t",                                                  "video/vnddlnampeg-tts"},
    {                    "dv",                                                             "video/x-dv"},
    {                   "lsf",                                                         "video/x-la-asf"},
    {                   "asf",                                                         "video/x-ms-asf"},
    {                   "xof",                                                         "x-world/x-vrml"}
};